Models/Equipe.cs
using System;
using System.Collections.Generic;
using System.IO;
using E_PlayersProjeto.Models;
using E_PlayersProjeto.Interfaces;

namespace E_PlayersProjeto.Models 
{
    public class Equipe : EPlayersBase, IEquipe
    {
        public int IdEquipe { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }

        private const string PATH = "Database/equipe.csv";
        /// <summary>
        /// Método construtor para Criar a pasta/arquivo
        /// </summary>
        public Equipe()
        {
            CreateFolderAndFile(PATH);
        }
        /// <summary>
        /// Criar equipe
        /// </summary>
        /// <param name="e">e</param>
        public void Create(Equipe e)
        {
            string[] linha = { PrepararLinha(e) };
            File.AppendAllLines(PATH, linha);
        }
        /// <summary>
        /// Preparar as linhas do CSV
        /// </summary>
        /// <param name="e">E</param>
        /// <returns>IdEquipe;Nome;Imagem</returns>

        private string PrepararLinha(Equipe e){
            return $"{e.IdEquipe};{e.Nome};{e.Imagem}";
        }
        /// <summary>
        /// Ler todas as linhas 
        /// </summary>
        /// <returns>Linhas lidas e adicionadas</returns>

        public List<Equipe> ReadAll()
        {
            List<Equipe> equipes = new List<Equipe>();
            string[] linhas = File.ReadAllLines(PATH);
            foreach (var item in linhas)
            {
                string[] linha = item.Split(";");
                Equipe equipe = new Equipe();
                equipe.IdEquipe = Int32.Parse(linha[0]);
                equipe.Nome = linha[1];
                equipe.Imagem = linha[2];

                equipes.Add(equipe);
            }
            return equipes;
        }
        /// <summary>
        /// Atulizar novas equipes
        /// </summary>
        /// <param name="e">E</param>

        public void Update(Equipe e)
        {
            List<String> linhas = ReadAllLinesCSV(PATH);
            // 2;FLA;flamengo.png
            linhas.RemoveAll(y => y.Split(";")[0] == e.IdEquipe.ToString() );
            linhas.Add( PrepararLinha(e) );
            RewriteCSV(PATH, linhas);
        }
        /// <summary>
        /// Apagar equipes
        /// </summary>
        /// <param name="IdEquipe">IdEquipe</param>

        public void Delete(int IdEquipe)
        {
            List<String> linhas = ReadAllLinesCSV(PATH);
            // 2;FLA;flamengo.png
            linhas.RemoveAll(y => y.Split(";")[0] == IdEquipe.ToString() );
            RewriteCSV(PATH, linhas);
        }
    }
}

Controllers/EquipeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using E_PlayersProjeto.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace E_PlayersProjeto.Controllers
{
    public class EquipeController : Controller
    {
        Equipe equipeModel = new Equipe();
        public IActionResult Index()
        {   
            ViewBag.Equipes = equipeModel.ReadAll();
            return View();
        }
        /// <summary>
        /// Cadastra e Cria o form fazendo a amarração com o frontend
        /// </summary>
        /// <param name="form">Form</param>
        /// <returns></returns>
        public IActionResult Cadastrar(IFormCollection form)
        {
            Equipe novaEquipe   = new Equipe();
            novaEquipe.IdEquipe = Int32.Parse(form["IdEquipe"]);
            novaEquipe.Nome     = form["Nome"];
            // Upload Inicio
            var file    = form.Files[0];
            var folder  = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");

            if(file != null)
            {
                if(!Directory.Exists(folder)){
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))  
                {  
                    file.CopyTo(stream);  
                }
                novaEquipe.Imagem   = file.FileName;
            }
            else
            {
                novaEquipe.Imagem   = "padrao.png";
            }
            // Upload Final

            equipeModel.Create(novaEquipe);            
            ViewBag.Equipes = equipeModel.ReadAll();

            return LocalRedirect("~/Equipe");
        }
        /// <summary>
        /// Método que ira excluir os objetos cadastraddos
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        [Route("[controller]/{id}")]
        public IActionResult Excluir(int id)
        {
            equipeModel.Delete(id);
            ViewBag.Equipes = equipeModel.ReadAll();
            return LocalRedirect("~/Equipe");
        }

    }
}

Views/Equipe/index.cshtml
 @model Equipe
    @{
        ViewData["Title"] = "Equipes";

    <div class="titulo_pagina">
            <h1>cadastro de @ViewData["Title"]</h1>
        </div>
    <form class="cadastro" method="post" action="@Url.Action("Cadastrar")"enctype="multipart/form-data">
     
     <div class="campo">
    <label for= "IdNoticia">IdEquipe</label>
    <input type="text" name="IdEquipe" id = "Equipes"/>
    </div>
    <div class="campo">
    <label for = "Nome">Nome</label>
    <input type= "text" name="Nome" id= "Nome"/>
    </div>
    <div class="campo">
    <label for = "Imagem">Imagem</label>
    <input type="file" name="Imagem" id= "Imagem"/>
    </div>

    <button type="submit">Cadastrar</button>
</form>

<table class="table table-striped table-responsive">
    <thead>
        <th>ID</th>
        <th>Nome</th>
        <th>Imagem</th>
    </thead>
    <tbody>
        @foreach(Equipe item in ViewBag.equipes){
            <tr>
                <td>@item.IdEquipe</td>
                <td>@item.Nome</td>

                <td><img src="img/Equipes/@item.Imagem" alt="Imagem da equipe @item.Nome" width="70"></td>
                <td><a asp-area="" asp-controller="Equipe" asp-action="Excluir" asp-route-id="@item.IdEquipe">
                 <i class="fa fa-trash"></i>   
                </a></td>
            </tr>
        }
    </tbody>
</table>
    }